### ISSUE TITLE
68030 bus error exception frame format

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/Moira#14]
Now I'm at the point where I need to create the bus error exception frame. Unfortunately, the user manual is very unspecific about what is really saved on the stack: 

<img width="342" alt="Bildschirmfoto 2022-09-22 um 20 53 40" src="https://user-images.githubusercontent.com/12561945/191849244-35ced8df-d9f6-4f32-882c-0eb9658e4990.png">

The most important entry is obviously the PC, because this entry is used by the `RTE` instruction to jump back into the program code. It has to point at the offending instruction. But what about the others? Does anybody know what's behind all those "internal registers"? I haven't been able to find more detailed information about the exception frame format.

**Comment by mras0** [comment]
I don't know about the internal registers, but there's some info in 8.2 (and a bit in 8.1.2). Also seems like there's a whdload QA slave that was used to check WinUAE's implementation: https://eab.abime.net/showpost.php?p=859567&postcount=120 (there's also more discussion later in the thread). Not sure how easy it would be to use that for testing though.

**Comment by dirkwhoffmann** [comment]
Closed as the MMU project is put on hold. 

For reference: 
Commit [115f803](https://github.com/dirkwhoffmann/vAmiga/tree/115f8039bea242786cd40cc3a9e67a8ba90c2d13) ist the last commit containing MMU code.
