### ISSUE TITLE
Breakpoints / Watchpoints are not detected after reset

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/Moira#3]
To speed up emulation, breakpoint checking is only performed if a specific flag is set:

```
    if (flags & CPU_CHECK_BP) {
        if (debugger.breakpointMatches(reg.pc)) {
            breakpointReached(reg.pc);
        } 
    }
```

During `reset()`, variable `flags` is set to a default value which has `CPU_CHECK_BP` and `CPU_CHECK_WP` set to 0. These flags must not be cleared if breakpoints / watchpoints are present.

**Comment by dirkwhoffmann** [comment]
Fixed with the latest merge from vAmiga.

**Comment by elmerucr** [comment]
Thanks for resolving this one! I noticed it in my latest build of E64-II.
