### ISSUE TITLE
MMU test programs needed

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/Moira#7]
In [this thread](https://github.com/dirkwhoffmann/vAmiga/issues/730) it was discussed to add MMU support to Moira.

I'd like to start by porting Musashi's MMU, but I am unsure about the best way to test the result. What is needed is an Amiga program which
- utilizes the MMU (obviously),
- is as simple as possible,
- is likely to break in the presence of bugs.

If somebody knows a good candidate, please let me know. 

Edit: An excellent article about how the MMU works can be found [here](https://mikro.naprvyraz.sk/docs/Coding/Atari/Maggie/MMU.TXT).

**Comment by dirkwhoffmann** [comment]
GigaMem could be a suitable test case: 

<img width="987" alt="Bildschirmfoto 2022-08-22 um 08 35 52" src="https://user-images.githubusercontent.com/12561945/185855778-a4791c74-fe27-460b-9625-20c91e94df4b.png">

**Comment by mras0** [comment]
I posted some suggestions in the other thread, but I think [mmu.library](http://aminet.net/package/util/libs/MMULib) would be a good starting point. It's still under active development (in fact it received a minor update 2 days) ago, should support all relevant configurations, and apart from libraries it also has a number of utilities related to MMU functionality. [MuManual](http://aminet.net/package/docs/misc/MuManual) has source code for some of them (and header files for using the library).

The readme also list some other programs using the MMU: Enforcer,CyberGuard,GuardianAngle,SetCPU,Shapeshifter,VMM, and GigaMem. [WHDLoad](http://whdload.de/docs/en/mmu.html) is another important user.

After installation you can run `SYS:MuTools/MuScan`. For more advanced testing, run `MuForce` in one window and `MuGuardianAngle` in another (to test memory protection). The tools are a bit advanced, but there's pretty decent documentation.

**Comment by dirkwhoffmann** [comment]
Closed as the MMU project is put on hold. 

For reference: 
Commit [115f803](https://github.com/dirkwhoffmann/vAmiga/tree/115f8039bea242786cd40cc3a9e67a8ba90c2d13) ist the last commit containing MMU code.
